version: 0.2
phases:
  build:
    commands:
      - aws deploy push --application-name h4b-app --s3-location s3://h4b-sugihara-artifact/artifact.zip --source src
artifacts:
  files:
    - '**/*' 
  base-directory: src